import static prePostInit.Recipemaps.*
import static gregtech.api.GTValues.*

// Formic acid

BR.recipeBuilder()
    .inputs(ore('dustAnyPuritySodium'))
    .fluidInputs(fluid('methanol') * 1000)
    .outputs(metaitem('dustSodiumMethoxide') * 6)
    .fluidOutputs(fluid('hydrogen') * 1000)
    .duration(80)
    .EUt(VA[LV])
    .buildAndRegister()

BCR.recipeBuilder()
    .inputs(ore('dustSodiumMethoxide'))
    .fluidInputs(fluid('polyethylene_glycol') * 50)
    .fluidInputs(fluid('methanol') * 1000)
    .fluidInputs(fluid('carbon_monoxide') * 1000)
    .fluidOutputs(fluid('methyl_formate_solution') * 1000)
    .duration(80)
    .EUt(VA[LV])
    .buildAndRegister()

CSTR.recipeBuilder()
    .notConsumable(ore('springCupronickel'))
    .fluidInputs(fluid('methyl_formate_solution') * 300)
    .fluidInputs(fluid('sulfuric_acid') * 50)
    .fluidOutputs(fluid('neutralized_methyl_formate_solution') * 300)
    .duration(4)
    .EUt(VA[LV])
    .buildAndRegister()

CSTR.recipeBuilder()
    .fluidInputs(fluid('water') * 150)
    .fluidInputs(fluid('neutralized_methyl_formate_solution') * 50)
    .fluidInputs(fluid('sulfuric_acid') * 50)
    .fluidOutputs(fluid('hydrolyzed_methyl_formate_solution') * 200)
    .duration(4)
    .EUt(VA[LV])
    .buildAndRegister()

DT.recipeBuilder()
    .fluidInputs(fluid('hydrolyzed_methyl_formate_solution') * 4000)
    .chancedOutput(metaitem('dustSodiumSulfate'), 5250, 0)
    .fluidOutputs(fluid('sulfuric_acid') * 1000)
    .fluidOutputs(fluid('polyethylene_glycol') * 50)
    .fluidOutputs(fluid('formic_acid_water_azeotrope') * 1000)
    .fluidOutputs(fluid('water') * 2600)
    .fluidOutputs(fluid('methanol') * 600)
    .duration(80)
    .EUt(VA[LV])
    .buildAndRegister()

VACUUM_DT.recipeBuilder()
    .fluidInputs(fluid('formic_acid_water_azeotrope') * 1000)
    .fluidOutputs(fluid('formic_acid') * 600)
    .fluidOutputs(fluid('water') * 400)
    .duration(80)
    .EUt(VA[LV])
    .buildAndRegister()

// Acetic acid (biological)

FERMENTER.recipeBuilder()
    .fluidInputs(fluid('ethanol') * 8000)
    .fluidInputs(fluid('oxygen') * 4000)
    .fluidOutputs(fluid('vinegar') * 16000)
    .duration(2400)
    .EUt(16)
    .buildAndRegister()

FERMENTER.recipeBuilder()
    .fluidInputs(fluid('ethanol') * 8000)
    .fluidInputs(fluid('air') * 12000)
    .fluidOutputs(fluid('vinegar') * 16000)
    .duration(2400)
    .EUt(16)
    .buildAndRegister()

FERMENTER.recipeBuilder()
    .fluidInputs(fluid('impure_ethanol') * 16000)
    .fluidInputs(fluid('oxygen') * 4000)
    .fluidOutputs(fluid('vinegar') * 16000)
    .duration(2400)
    .EUt(16)
    .buildAndRegister()

FERMENTER.recipeBuilder()
    .fluidInputs(fluid('impure_ethanol') * 16000)
    .fluidInputs(fluid('air') * 12000)
    .fluidOutputs(fluid('vinegar') * 16000)
    .duration(2400)
    .EUt(16)
    .buildAndRegister()

DT.recipeBuilder()
    .fluidInputs(fluid('vinegar') * 2000)
    .outputs(metaitem('dustWood'))
    .fluidOutputs(fluid('acetic_acid') * 400)
    .fluidOutputs(fluid('water') * 1600)
    .duration(200)
    .EUt(VA[LV])
    .buildAndRegister()

DT.recipeBuilder()
    .fluidInputs(fluid('gtfo_apple_cider') * 2000)
    .fluidOutputs(fluid('acetic_acid') * 400)
    .fluidOutputs(fluid('water') * 1600)
    .duration(200)
    .EUt(VA[LV])
    .buildAndRegister()

// Acetic Acid (chemical)
// Source: Acetic Acid Chapter in Ullmann's Encyclopedia of Industrial Chemistry https://doi.org/10.1002/14356007.a01_045

// Oxidation of Acetaldehyde
CSTR.recipeBuilder()
    .circuitMeta(1)
    .notConsumable(ore('dustCobaltIiAcetate'))
    .fluidInputs(fluid('gtfo_acetaldehyde') * 50)
    .fluidInputs(fluid('oxygen') * 50)
    .fluidOutputs(fluid('acetic_acid') * 50)
    .duration(5)
    .EUt(VA[MV])
    .buildAndRegister()

// Monsanto Process
DISTILLERY.recipeBuilder() // Source: Platinum Group Metals and Compounds Chapter in Ullmann's Encyclopedia of Industrial Chemistry https://doi.org/10.1002/14356007.a21_075
    .fluidInputs(fluid('hexachlororhodic_acid_solution') * 8950)
    .fluidInputs(fluid('hydrochloric_acid') * 4500)
    .chancedOutput(metaitem('dustRhodiumIiiChlorideTrihydrate') * 7, 5000, 0)
    .fluidOutputs(fluid('diluted_hydrochloric_acid') * 6000)
    .duration(200)
    .EUt(VA[MV])
    .buildAndRegister()

CSTR.recipeBuilder() // Simulates the reaction that would typically occur in-situ (Source: https://technology.matthey.com/content/journals/10.1595/003214000X44394105)
    .fluidInputs(fluid('methanol') * 100)
    .fluidInputs(fluid('hydroiodic_acid') * 100)
    .fluidOutputs(fluid('methyl_iodide_solution') * 200)
    .duration(10)
    .EUt(VA[LV])
    .buildAndRegister()

BR.recipeBuilder() // Source: Lithium and Lithium Compounds. Chapter in Ullmann's Encyclopedia of Industrial Chemistry https://doi.org/10.1002/14356007.a15_393
    .inputs(ore('dustLithiumHydroxide') * 3)
    .fluidInputs(fluid('hydroiodic_acid') * 1000)
    .fluidOutputs(fluid('lithium_iodide_solution') * 2000)
    .EUt(VA[LV])
    .duration(160)
    .buildAndRegister()

LCR.recipeBuilder()
    .notConsumable(fluid('methyl_iodide_solution') * 2000)
    .notConsumable(ore('dustRhodiumIiiChlorideTrihydrate'))
    .notConsumable(fluid('lithium_iodide_solution') * 2000)
    .fluidInputs(fluid('methanol') * 1000)
    .fluidInputs(fluid('carbon_monoxide') * 1000) // Possibly should be high-pressure? Currently unobtainable though
    .fluidOutputs(fluid('acetic_acid') * 1000)
    .duration(4)
    .EUt(VA[EV])
    .buildAndRegister()

// Cativa Process

// 2H2IrCl6 + H2C2O4 -> 2H3IrCl6 + 2CO2
BR.recipeBuilder() // Source: https://patents.justia.com/patent/20190337819
    .fluidInputs(fluid('hexachloroiridic_acid_solution') * 4000)
    .inputs(ore('dustOxalicAcid') * 8)
    .fluidOutputs(fluid('hexachloroiridic_iii_acid_solution') * 4000)
    .fluidOutputs(fluid('carbon_dioxide') * 2000)
    .duration(160)
    .EUt(VA[LV])
    .buildAndRegister()

DISTILLERY.recipeBuilder()
    .fluidInputs(fluid('hexachloroiridic_iii_acid_solution') * 2000)
    .fluidInputs(fluid('hydrochloric_acid') * 9000)
    .outputs(metaitem('dustIridiumIiiChlorideTrihydrate') * 7)
    .fluidOutputs(fluid('diluted_hydrochloric_acid') * 12000)
    .duration(100)
    .EUt(VA[MV])
    .buildAndRegister()

LCR.recipeBuilder()
    .notConsumable(fluid('methyl_iodide_solution') * 2000)
    .notConsumable(ore('dustIridiumIiiChlorideTrihydrate'))
    .fluidInputs(fluid('methanol') * 1000)
    .fluidInputs(fluid('carbon_monoxide') * 1000)
    .fluidOutputs(fluid('acetic_acid') * 1000)
    .duration(2)
    .EUt(VA[IV])
    .buildAndRegister()

// Fatty acids

    // Oleic/linoleic acid

    AUTOCLAVE.recipeBuilder()
        .fluidInputs(fluid('distilled_water') * 3000)
        .fluidInputs(fluid('seed_oil') * 1000)
        .fluidOutputs(fluid('glycerol') * 1000)
        .fluidOutputs(fluid('fatty_acid_solution') * 3000)
        .EUt(VA[LV])
        .duration(200)
        .buildAndRegister()

    CRYSTALLIZER.recipeBuilder()
        .fluidInputs(fluid('fatty_acid_solution') * 1000)
        .fluidInputs(fluid('methanol') * 1000)
        .inputs(ore('dustUrea'))
        .fluidOutputs(fluid('oleic_acid_solution') * 1000)
        .EUt(VA[LV])
        .duration(200)
        .buildAndRegister()

    CRYSTALLIZER.recipeBuilder()
        .fluidInputs(fluid('oleic_acid_solution') * 1000)
        .outputs(metaitem('dustOleicAcid'))
        .fluidOutputs(fluid('methanol') * 1000)
        .EUt(VA[LV])
        .duration(200)
        .buildAndRegister()

    // Liquid Oleic Acid * 144
    mods.gregtech.extractor.removeByInput(30, [metaitem('dustOleicAcid')], null)

    EXTRACTOR.recipeBuilder()
        .inputs(ore('dustOleicAcid'))
        .fluidOutputs(fluid('oleic_acid') * 1000)
        .duration(5)
        .EUt(VA[LV])
        .buildAndRegister()

    MIXER.recipeBuilder()
        .fluidInputs(fluid('sodium_hydroxide_solution') * 1000)
        .inputs(ore('dustOleicAcid'))
        .fluidOutputs(fluid('alkaline_sodium_oleate_solution') * 1000)
        .EUt(VA[LV])
        .duration(80)
        .buildAndRegister()

    // Coconut acids (majority saturated)

    furnace.add(metaitem('gregtechfoodoption:component.coconut'), metaitem('copra'))

    EXTRACTOR.recipeBuilder()
        .inputs(metaitem('copra'))
        .fluidOutputs(fluid('coconut_oil') * 50)
        .EUt(VA[LV])
        .duration(80)
        .buildAndRegister()

    AUTOCLAVE.recipeBuilder()
        .fluidInputs(fluid('distilled_water') * 3000)
        .fluidInputs(fluid('coconut_oil') * 1000)
        .fluidOutputs(fluid('glycerol') * 1000)
        .fluidOutputs(fluid('coconut_acid') * 3000)
        .EUt(VA[LV])
        .duration(200)
        .buildAndRegister()
    
    SIEVE_DT.recipeBuilder()
        .fluidInputs(fluid('dense_steam') * 1000)
        .fluidInputs(fluid('coconut_acid') * 1000)
        .fluidOutputs(fluid('oleic_acid') * 75)
        .fluidOutputs(fluid('palmitic_acid') * 105)
        .fluidOutputs(fluid('myristic_acid') * 175)
        .fluidOutputs(fluid('lauric_acid') * 485)
        .fluidOutputs(fluid('capric_acid') * 85)
        .fluidOutputs(fluid('caprylic_acid') * 75)
        .duration(80)
        .EUt(VA[LV])
        .buildAndRegister()
