import static gregtech.api.GTValues.*

SIFTER = recipemap('sifter')
BR = recipemap('batch_reactor')
MIXER = recipemap('mixer')
DRYER = recipemap('dryer')

MIXER.recipeBuilder()
    .fluidInputs(fluid('distilled_water') * 10000)
    .fluidInputs(fluid('naphthenic_acid') * 1000)
    .fluidInputs(fluid('coconut_acid') * 2000)
    .inputs(ore('dustOleicAcid'))
    .inputs(ore('dustSodiumHydroxide') * 12)
    .fluidOutputs(fluid('impure_sodium_soap_solution') * 10000)
    .duration(200)
    .EUt(VA[MV])
    .buildAndRegister()

BR.recipeBuilder()
    .fluidInputs(fluid('impure_sodium_soap_solution') * 10000)
    .inputs(ore('dustActivatedCarbon') * 4)
    .fluidOutputs(fluid('clarified_sodium_soap_solution') * 10000)
    .duration(200)
    .EUt(VA[MV])
    .buildAndRegister()

SIFTER.recipeBuilder()
    .fluidInputs(fluid('clarified_sodium_soap_solution') * 10000)
    .notConsumable(metaitem('item_filter'))
    .fluidOutputs(fluid('sodium_soap_solution') * 10000)
    .outputs(metaitem('dustSpentActivatedCarbon') * 4)
    .duration(200)
    .EUt(VA[MV])
    .buildAndRegister()

MIXER.recipeBuilder()
    .fluidInputs(fluid('sodium_soap_solution') * 10000)
    .inputs(metaitem('dustDiatomite') * 8)
    .fluidOutputs(fluid('clear_sodium_soap_solution') * 10000)
    .duration(200)
    .EUt(VA[MV])
    .buildAndRegister()

BR.recipeBuilder()
    .fluidInputs(fluid('clear_sodium_soap_solution') * 5000)
    .fluidInputs(fluid('aluminium_sulfate_solution') * 2000)
    .fluidOutputs(fluid('wastewater') * 7000)
    .outputs(metaitem('dustImpureAluminiumSoap'))
    .duration(200)
    .EUt(VA[MV])
    .buildAndRegister()

MIXER.recipeBuilder()
    .fluidInputs(fluid('distilled_water') * 7000)
    .inputs(metaitem('dustDiatomite') * 4)
    .inputs(metaitem('dustImpureAluminiumSoap'))
    .fluidOutputs(fluid('colloidal_aluminium_soap') * 7000)
    .duration(200)
    .EUt(VA[MV])
    .buildAndRegister()

SIFTER.recipeBuilder()
    .fluidInputs(fluid('colloidal_aluminium_soap') * 7000)
    .notConsumable(metaitem('item_filter'))
    .fluidOutputs(fluid('wastewater') * 7000)
    .outputs(metaitem('dustWetAluminiumSoap'))
    .duration(200)
    .EUt(VA[MV])
    .buildAndRegister()

DRYER.recipeBuilder()
    .inputs(metaitem('dustWetAluminiumSoap'))
    .outputs(metaitem('dustNapalmGellingAgent'))
    .duration(200)
    .EUt(VA[MV])
    .buildAndRegister()

MIXER.recipeBuilder()
    .fluidInputs(fluid('gasoline') * 8000)
    .inputs(metaitem('dustNapalmGellingAgent'))
    .fluidOutputs(fluid('napalm') * 8000)
    .duration(200)
    .EUt(VA[MV])
    .buildAndRegister()