name = "Supersymmetry"
author = "SymmetricDevs"
version = "0.1.15.12"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a9bdbb2607a4c8c9d844cac650f0bc71d97b366dd0e5e30478354c71ab3778b6"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
