name = "Supersymmetry"
author = "SymmetricDevs"
version = "0.1.16.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8c636bbda49a2bbfd859ba9b984b87e2f0abda95953f170d0015545ff0429977"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
