import static prePostInit.Recipemaps.*
import static gregtech.api.GTValues.*

MIXER.recipeBuilder()
    .inputs(ore('dustPitch'))
    .inputs(ore('dustCoke') * 9)
    .outputs(metaitem('carbon_paste') * 5)
    .EUt(VA[LV])
    .duration(60)
    .buildAndRegister()

MIXER.recipeBuilder()
    .inputs(ore('dustPitch'))
    .inputs(ore('dustHeatedGreenCoke') * 9)
    .outputs(metaitem('carbon_paste') * 10)
    .EUt(VA[LV])
    .duration(60)
    .buildAndRegister()

EXTRUDER.recipeBuilder()
    .notConsumable(metaitem('shape.extruder.rod'))
    .inputs(metaitem('carbon_paste'))
    .outputs(metaitem('raw_electrode'))
    .EUt(VA[LV])
    .duration(50)
    .buildAndRegister()

FORMING_PRESS.recipeBuilder()
    .inputs(metaitem('carbon_paste') * 7)
    .notConsumable(metaitem('shape.mold.crucible'))
    .outputs(metaitem('raw_carbon_crucible'))
    .EUt(VA[LV])
    .duration(100)
    .buildAndRegister()

FORMING_PRESS.recipeBuilder()
    .inputs(metaitem('carbon_paste') * 7)
    .notConsumable(metaitem('shape.mold.block'))
    .outputs(metaitem('raw_carbon_crucible'))
    .EUt(VA[LV])
    .duration(100)
    .buildAndRegister()

MIXER.recipeBuilder()
    .fluidInputs(fluid('water') * 100)
    .inputs(metaitem('dustFireclay'))
    .inputs(metaitem('dustGraphite'))
    .outputs(metaitem('clay_graphite_paste'))
    .EUt(VA[LV])
    .duration(50)
    .buildAndRegister()

FORMING_PRESS.recipeBuilder()
    .inputs(metaitem('clay_graphite_paste') * 7)
    .notConsumable(metaitem('shape.mold.crucible'))
    .outputs(metaitem('raw_clay_graphite_crucible'))
    .EUt(VA[LV])
    .duration(100)
    .buildAndRegister()

MILLING.recipeBuilder()
    .inputs(metaitem('clay_graphite_paste') * 7)
    .notConsumable(metaitem('shape.mold.crucible'))
    .outputs(metaitem('raw_clay_graphite_crucible'))
    .EUt(VA[LV])
    .duration(100)
    .buildAndRegister()